### ISSUE TITLE
No way to set endians?

### ISSUE THREAD

**Issue by belldandu** [olve/struct.js#4]
I have looked at your readme and your code and i don't see a way to specify what endian we want to use. So far your library is the only one that might properly work in a browser but it falls short compared to bufferpack and jspack because it lacks the ability to choose endians.

I honestly hope someone could fully make a 1 file javascript file that mimicks pythons struct module completely and does not use nodes built in buffer library because that's not available in browsers. Bufferpack was good for me when i only needed node but now i need something that also supports browsers that does not use functions that aren't available in a browser.

**Comment by olve** [comment]
struct.push and struct.get take a third boolean argument: littleEndian

```
//big endian
var struct = new Struct();
struct.push("H", 10000);
console.log(struct.array); // --> [39, 16]

//little endian
var struct = new Struct();
struct.push("H", 10000, true);
console.log(struct.array); // --> [16, 39]
console.log(struct.get("H", 0)); // --> 4135
console.log(struct.get("H", 0, true)); // --> 10000
```

struct.set is only a syntax-wrapper for DataView prototype setter-methods (setUint8, setInt16, etc), and does not implement handling of endians; probably should. 

I will update the README to cover this.

**Comment by belldandu** [comment]
Thank you.
