### ISSUE TITLE
No support for I and i? Also can we do stuff like 4b, 4i, etc...? Missing some Format Options.

### ISSUE THREAD

**Issue by belldandu** [olve/struct.js#5]
One of the libraries i made used to use bufferpack however i ditched it because it doesn't work in a browser. I noticed that you dont have i or I in your list of supported methods. There is also no information on whether we can specify a number before a letter.

Some format options that are available in python are not here. Are there any plans to add them?

**Comment by belldandu** [comment]
See https://docs.python.org/3/library/struct.html#format-characters

**Comment by olve** [comment]
i and I were discarded because they perform the same function as l and L.
Substitute i/I with l/L in your code.

As for further format options; make a pull-request. I have no plans to add more.
